### ISSUE TITLE
User Sign up error handling

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#14]
_From @nandkumarj on May 29, 2018 7:11_

Right now for varierty of failures , there is a same error message for user signup failure.  There should be different messages for different failures.

_Copied from original issue: vanlittle/VNF-Onboarding#63_

**Comment by nandkumarj** [comment]
Even though this issue is opened to provide appropriate errors/reasons for user signup failure. To address this  there needs to error handling at the backend and it needs to be made sure that those errors are propagated to frontend. To do that we need to take a holistic approach and have some sort of 
error handling/reporting framework at the backend. Which should be usable by every backend component. Error handling or reporting was defferred because it could not be accomodated in phase-2 timeline.

**Comment by ljilluzzi** [comment]
Analysis underway. Shoot for 10/01 demo to resolve

**Comment by nandkumarj** [comment]
Messages/Errors for following scenarios
1. User Registration and send email succeeded
2. User Registration succeeded but Email Functionality is disabled
3. User Registration suceeded but  Send Email Failed
4. User Registation failed because user or mail id already exists

**Comment by varadep** [comment]
Also add
5. User Registration failed because database connectivity
6. User Registration failed backend connectivity
