### ISSUE TITLE
RIFTware does not handle package generation for VCD

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#22]
_From @nandkumarj on April 9, 2018 12:31_

_Copied from original issue: vanlittle/VNF-Onboarding#40_

**Comment by nandkumarj** [comment]
I remember bringing it to Akshay's notice. That time this wasn't addressed because Akshay did not have testbed to try out VCD blueprint.
This is an old issue. And Riftware in the context of VNF Onboarding tool is miles behind. It wouldn't make sense to address this in isolation. My plan is to take this up as and when MultiVDU feature for Riftware is touched. That would also mean that in terms of effort , changes and new code MultiVDU Riftware could turn out heavier than other orchestrators.

**Comment by nandkumarj** [comment]
VCD is not supported by Riftware, hence closing this issue
