### ISSUE TITLE
custom flavor doesn"t work

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#27]
_From @ciberkot on February 27, 2018 14:9_

if i choose custom flavor it is inactive.

_Copied from original issue: vanlittle/VNF-Onboarding#23_

**Comment by nandkumarj** [comment]
Assinging it to myself for the timebeing. Development effort for Rift has been lagging because of variety of reasons. Will need to look at Rift issues holistically . This issue has been there since the time VNF ONboarding tool was supporting single VDU VNF. I think it will make sense to address Riftware pending issues as and when MultiVDU feature for Rift is taken up.

**Comment by nandkumarj** [comment]
Riftware Development is being tracked under #37. So duping this to #37.

**Comment by nandkumarj** [comment]
This is a duplicate. So closing.

**Comment by nandkumarj** [comment]
This is implemented and tested, hence closing this issue.
