### ISSUE TITLE
RIFT with Openstack EPA configurations are skipped

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#29]
_From @vanlittle on February 26, 2018 12:57_

Enable EPA configurations for Rift.ware orchestrator with openstack

_Copied from original issue: vanlittle/VNF-Onboarding#19_

**Comment by nandkumarj** [comment]
Assinging it to myself for the timebeing. Development effort for Rift has been lagging because of variety of reasons. Will need to look at Rift issues holistically . This issue has been there since the time VNF ONboarding tool was supporting single VDU VNF. I think it will make sense to address Riftware pending issues as and when MultiVDU feature for Rift is taken up.

**Comment by nandkumarj** [comment]
Development  effort for riftware support is being tracked under #37. So closing this one.

**Comment by nandkumarj** [comment]
Development and testing complete for adding EPA parameters to Riftware.
